#!/usr/bin/env node
/**
 * Builds docs/UX-AUDIT.md from the functional action audit results
 * (test-results/action-audit.json, written by e2e/90-action-audit.spec.ts).
 *
 *   node scripts/audit-report.mjs [after.json] [before.json]
 *
 * The "before" run is optional; when given, the report compares the two.
 */
import fs from 'node:fs';

const [afterPath = 'test-results/action-audit.json', beforePath] = process.argv.slice(2);
const load = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));
const after = load(afterPath);
const before = beforePath && fs.existsSync(beforePath) ? load(beforePath) : null;

const STATUSES = ['WORKING', 'DISABLED', 'UNREACHABLE', 'NO_EFFECT', 'BROKEN', 'WRONG_PERMISSION'];
const count = (rows, key = 'status') => rows.reduce((m, r) => ((m[r[key]] = (m[r[key]] ?? 0) + 1), m), {});
// Hotel ids differ per run; keep the screen path only.
const screen = (route) => route.replace(/^\/admin\/h\/[^/]+/, '/admin/h/:hid').replace(/^\/h\/[^/?]+/, '/h/:slug');

const out = [];
const line = (s = '') => out.push(s);

line('# Functional action audit');
line();
line('This file is generated by `node scripts/audit-report.mjs` from `test-results/action-audit.json`. Do not edit it by hand.');
line();
line('The audit is produced by `e2e/90-action-audit.spec.ts`. For each role, it:');
line('- signs in;');
line('- opens every screen the role can reach;');
line('- clicks every visible control in the main area;');
line('- records what actually happened: navigation, API call, dialog, download, file chooser, new tab or DOM change.');
line();
line('It covers the admin roles plus a guest on a 390 px phone. It runs against the disposable E2E database.');
line();
line(`Run: ${after.generated}`);
line();

line('## Summary');
line();
const a = count(after.results);
const b = before ? count(before.results) : null;
line(`| Status | ${before ? 'Before | ' : ''}After | Meaning |`);
line(`|---|${before ? '---|' : ''}---|---|`);
const MEANING = {
  WORKING: 'Produced an observable effect',
  DISABLED: 'Correctly disabled in the current state (e.g. Save with no changes, Move up on the first row)',
  UNREACHABLE: 'Present but covered or off-screen at that moment (not clickable by a user either)',
  NO_EFFECT: 'Clickable but nothing happened: a dead control',
  BROKEN: 'Triggered a 5xx or a network failure',
  WRONG_PERMISSION: 'A visible control led to a 403',
};
for (const s of STATUSES) line(`| ${s} | ${before ? `${b[s] ?? 0} | ` : ''}${a[s] ?? 0} | ${MEANING[s]} |`);
line(`| **Total controls** | ${before ? `${before.results.length} | ` : ''}${after.results.length} | |`);
line();
const loadErrors = after.routes.filter((r) => r.loadErrors.length);
line(`- Screens visited: **${after.routes.length}**, with **${loadErrors.length}** load errors.`);
if (before) line(`- Before, the run covered ${before.routes.length} screens with ${before.routes.filter((r) => r.loadErrors.length).length} load errors.`);
line();

line('## By role');
line();
line('Coverage depth by role:');
line('- **Deep** (Hotel Admin, Platform Finance, Hotel Finance, guest): every control on every reachable screen is clicked.');
line('- **Shallow** (Super Admin and the department roles):');
line('  - every reachable screen is loaded and checked for API errors, including 403s from calls the screen makes by itself;');
line('  - controls are not clicked again, because they are the same components the Hotel Admin crawl clicks;');
line('  - their scoping is covered separately by `e2e/06-admin-language-permissions.spec.ts` (exact navigation, refused screens, server 403).');
line();
line('| Role | Screens | Controls | Working | Disabled | Unreachable | Dead / broken / forbidden |');
line('|---|---|---|---|---|---|---|');
const roles = [...new Set(after.routes.map((r) => r.role))];
for (const role of roles) {
  const rows = after.results.filter((r) => r.role === role);
  const c = count(rows);
  const bad = (c.NO_EFFECT ?? 0) + (c.BROKEN ?? 0) + (c.WRONG_PERMISSION ?? 0);
  line(`| ${role} | ${after.routes.filter((r) => r.role === role).length} | ${rows.length} | ${c.WORKING ?? 0} | ${c.DISABLED ?? 0} | ${c.UNREACHABLE ?? 0} | ${bad} |`);
}
line();

const problems = after.results.filter((r) => ['NO_EFFECT', 'BROKEN', 'WRONG_PERMISSION'].includes(r.status));
line('## Open findings');
line();
if (!problems.length) line('None. Every visible control produced a real effect, and no control led to a server error or a forbidden call.');
else {
  line('| Role | Screen | Control | Status | Detail |');
  line('|---|---|---|---|---|');
  for (const p of problems) line(`| ${p.role} | \`${screen(p.route)}\` | ${p.control} | ${p.status} | ${(p.detail ?? '').replace(/\|/g, '\\|')} |`);
}
line();

if (before) {
  const fixed = before.results.filter((r) => ['NO_EFFECT', 'BROKEN', 'WRONG_PERMISSION'].includes(r.status));
  line('## Findings from the baseline run and how they were fixed');
  line();
  line('| Screen | Control | Before | Root cause | Fix |');
  line('|---|---|---|---|---|');
  for (const f of fixed) {
    const why = explain(screen(f.route), f.control, f.kind);
    line(`| \`${screen(f.route)}\` | ${f.control} | ${f.status} | ${why[0]} | ${why[1]} |`);
  }
  line();
}

line('### Found and fixed after the baseline run');
line();
line('| Screen | Finding | Root cause | Fix |');
line('|---|---|---|---|');
line('| `/admin/h/:hid/room-services` (Maintenance) | The screen loaded with `GET …/data/templates → 403` | The Excel buttons requested the import templates before checking the role, and Maintenance has no import module | The templates query is enabled only for roles with the import module (`useTemplates(hid, canImport)`) |');
line('| `/admin/platform/agreements` | "Platform default" and the hotel scope buttons showed no state | The selected scope was shown only by colour | The scope buttons expose `aria-pressed`; hotel names and rule counts are localised |');
line('| Several screens | Hotel, department, line-item and service names were English in the Arabic admin | Displays read `name_en` directly | They use `pickLang()`, falling back to English when no Arabic name exists |');
line('| Crawler | Named switches were reported as "(no accessible name)", and a role without hotel links hung the run | The crawler ignored `aria-labelledby` / `<label for>`, and waited for a link with no timeout | The crawler resolves accessible names like assistive technology does, and bounds that lookup |');
line();

line('## Screens');
line();
line('| Role | Screen | Heading | Controls |');
line('|---|---|---|---|');
for (const r of after.routes) line(`| ${r.role} | \`${screen(r.route)}\` | ${r.heading || '—'} | ${r.actions} |`);
line();

fs.writeFileSync('docs/UX-AUDIT.md', out.join('\n'));
console.log(`docs/UX-AUDIT.md: ${after.results.length} controls, ${problems.length} open findings`);

/** Root cause and fix for each class of baseline finding. */
function explain(route, control, kind) {
  if (kind === 'switch' && control.startsWith('(no accessible name)'))
    return ['The toggle had no accessible name, and the crawler read its state change through a label it could not reach.', 'The toggle is labelled by its visible label and help text (`aria-labelledby` / `aria-describedby`).'];
  if (/Hidden/.test(control) || /\/(spa|laundry)$/.test(route))
    return ['The selected category row re-rendered with nothing observable: no state was exposed, so a second click looked dead.', 'The selected row exposes `aria-current`, so the state is announced and the click is idempotent.'];
  if (/Mobile preview|Desktop preview|Tablet preview/.test(control))
    return ['The preview device switch did not expose which device was active.', 'The device buttons expose `aria-pressed`.'];
  if (/Move up|Move down/.test(control))
    return ['The first row could be moved up (and the last down), which did nothing.', 'These moves are disabled at the ends of the list.'];
  if (route.endsWith('/branding'))
    return ['The theme preview rendered real buttons (e.g. "Order to your room", "Add", "Hover state") that did nothing.', 'The preview mock-ups are inert, `aria-hidden` illustrations, not buttons.'];
  return ['—', '—'];
}
