/**
 * Collects every English message the API can return (HttpError helpers, field
 * errors, zod messages) so the admin can show them in Arabic. Run with --write
 * to regenerate src/admin/i18n/serverMessages.ts; the i18n test fails when the
 * catalogue is stale or a message lacks Arabic.
 */
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
const files = (d: string): string[] => fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? files(path.join(d, e.name)) : e.name.endsWith('.ts') ? [path.join(d, e.name)] : []));
const out = new Set<string>();
const CALLS = new Set(['badRequest', 'notFound', 'conflict', 'forbidden', 'unauthorized', 'tooMany', 'fieldError', 'HttpError']);
for (const f of [...files('server'), ...files('shared')]) {
  if (f.includes('/excel/') || f.includes('/seed/') || f.endsWith('cli.ts')) continue;
  const src = fs.readFileSync(f, 'utf8');
  const sf = ts.createSourceFile(f, src, ts.ScriptTarget.Latest, true);
  const lit = (a: ts.Node | undefined) => {
    if (!a) return;
    if (ts.isStringLiteral(a) || ts.isNoSubstitutionTemplateLiteral(a)) out.add(a.text);
    else if (ts.isTemplateExpression(a)) {
      let m = a.head.text;
      a.templateSpans.forEach((s, i) => (m += `{${i}}` + s.literal.text));
      out.add(m);
    } else if (ts.isConditionalExpression(a)) { lit(a.whenTrue); lit(a.whenFalse); }
  };
  const v = (n: ts.Node) => {
    if ((ts.isCallExpression(n) || ts.isNewExpression(n)) && ts.isIdentifier(n.expression) && CALLS.has(n.expression.text)) {
      const args = n.arguments ?? ts.factory.createNodeArray();
      lit(n.expression.text === 'HttpError' ? args[2] : n.expression.text === 'fieldError' ? args[1] : args[0]);
    }
    // zod messages: .min(1, 'Required'), refine(..., 'msg'), { message: '...' }, { error: '...' }
    if (ts.isCallExpression(n) && ts.isPropertyAccessExpression(n.expression) && ['min', 'max', 'regex', 'refine', 'email', 'uuid', 'url', 'length'].includes(n.expression.name.text)) {
      for (const a of n.arguments) if (ts.isStringLiteral(a) && /[A-Za-z]{2,} /.test(a.text)) out.add(a.text);
    }
    if (ts.isPropertyAssignment(n) && ['message', 'error'].includes(n.name.getText(sf)) && (ts.isStringLiteral(n.initializer) || ts.isTemplateExpression(n.initializer))) lit(n.initializer);
    ts.forEachChild(n, v);
  };
  v(sf);
}
const list = [...out].filter((m) => /[A-Za-z]{2,}/.test(m)).sort();
if (process.argv.includes('--write')) {
  fs.writeFileSync('src/admin/i18n/serverMessages.ts', `/** Generated by scripts/extract-server-messages.ts — English API messages the admin translates. */\nexport const SERVER_MESSAGES: string[] = ${JSON.stringify(list, null, 2)};\n`);
}
export { list };
console.log(list.length);
